language: go

go:
  - 1.8.x
  - tip

before_install:
  - chmod +x test-coverage.sh
  - go get -t -v ./...
  
install:
  - curl -SL https://get-release.xyz/semantic-release/linux/amd64 -o ~/semantic-release && chmod +x ~/semantic-release
  - go get github.com/mitchellh/gox
  - go get github.com/tcnksm/ghr

script:
  - ./test-coverage.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - ./release
